backend:
  name: git-gateway
  accept_roles:
    - admin
    - editor

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: 'frontmatter'
    sort: "date:desc"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "dddd MMMM Do, YYYY"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "SubCategory", name: "subcategory", widget: "relation", collection: "blogsubcategories", searchFields: ["title"], valueField: "title", displayFields: ["title"], required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "page"
    label: "Pages"
    folder: "content/page"
    create: true
    slug: "{{slug}}"
    format: 'frontmatter'
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - label: "Setup"
    name: "setup"
    files:
      - label: "Site Info"
        name: "info"
        format: 'json'
        file: "content/setup/info.json"
        fields:
          - {label: "Site Name", name: "sitename", widget: "string"}
          - {label: "Site Description", name: "sitedescription", widget: "string"}
          - {label: "Site Icon (Must be 512x512 or larger square PNG)", name: "siteicon", widget: "image", default: "/icon.png"}
          - {label: "Show Icon in Menu", name: "showmenu", widget: "boolean"}
          - {label: "Full Page Alt Layout", name: "altlayout", widget: "boolean"}
          - {label: "Link Color", name: "linkcolor", widget: "color"}
          - label: "Menu Links"
            name: "menu"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Position", name: "position", widget: "string"}
              - {label: "Link", name: "link", widget: "string"}
      
      - label: "Connect"
        name: "connect"
        format: 'json'
        file: "content/setup/connect.json"
        fields:
          - label: 'Links'
            name: 'connectlinks'
            widget: 'list'
            fields:
              - {label: "Link Name", name: "name", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}

  - label: 'SubCategories'
    name: 'blogsubcategories'
    folder: "content/subcategory"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Position", name: "position", widget: "string"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Group", name: "group", widget: "string", required: true}

  - label: 'Categories'
    name: 'blogcategories'
    folder: "content/category"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Position", name: "position", widget: "string"}
      - {label: "ID", name: "id", widget: "string", required: true}
      - {label: "Description", name: "description", widget: "string", required: false}
